version: '3'

services:
  db:
    hostname: db
    build: 
      context: './db'
      args:
        - DB_RUN_AS=${DB_RUN_AS}
    restart: always   
    user: ${DB_RUN_AS}
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  guacd:
    hostname: guacd
    user: ${GUACD_RUN_AS}
    restart: always
    build: 
      context: './guacd'
      args:
        - GUACD_RUN_AS=${GUACD_RUN_AS}

  guacui:
    hostname: guacui
    user: ${GUACUI_RUN_AS}
    restart: always
    ports:
      - 8080:8080
    links:
      - guacd
      - db
    build:
      context: './guacui'
      args:
        - GUACUI_RUN_AS=${GUACUI_RUN_AS}
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      GUACAMOLE_HOME: /config
    volumes:
      - ${GUAC_CONFIG_DIR}:/config

volumes:
  data:
